# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ghost Hunter
email: support@dc.net9.org
description: > # this means to ignore newlines until "baseurl:"
  Ghost Hunter 中微子数据分析排位赛
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ghost-hunter-contest.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
